version: "3"

services:

  kie-server:
    image: kie-server-umu
    build: ./kie-server
    ports:
      - "8180:8080"
    container_name: kie-server
    networks:
      internal:
        ipv4_address: 192.168.7.3

  business-central: 
    image: business-central-umu
    build: ./business-central
    ports:
      - "8080:8080"
      - "8001:8001"
    container_name: drools-workbench
    networks:
      internal:
        ipv4_address: 192.168.7.2

  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - "55555:8080"
    container_name: swagger
    environment:
      - SWAGGER_FILE=./doc/doc.yaml
    networks:
      internal:
        ipv4_address: 192.168.7.4



networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.7.0/24
          gateway: 192.168.7.1 

