version: '3'

services:
  business-central:
    build: ./business-central
    image: business-central-xd
    ports:
    - 8080:8080
    - 8001:8001
  kie-server:
    build: ./kie-server
    image: kie-server
    environment:
      KIE_SERVER_LOCATION: http://kie-server:8080/kie-server/services/rest/server
      KIE_SERVER_CONTROLLER: http://business-central:8080/business-central/rest/controller
      KIE_MAVEN_REPO: http://business-central:8080/business-central/maven2
      KIE_MAVEN_REPO_USER: admin
      KIE_MAVEN_REPO_PWD: admin
      KIE_SERVER_PWD: kieserver1!
      KIE_SERVER_USER: kieserver
      KIE_SERVER_CONTROLLER_USER: admin
      KIE_SERVER_CONTROLLER_PWD: admin
    ports:
      - 8180:8080
    depends_on:
      - business-central
