//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationCondition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isCNF" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationCondition", propOrder = {
    "isCNF"
})
@XmlSeeAlso({
    PolicyDependencyCondition.class,
    FiveGSecuritySliceCondition.class,
    PurposeCondition.class,
    DataAgreggationConfigurationConditions.class,
    MonitoringConfigurationConditions.class,
    NetworkSlicingConfigurationCondition.class,
    AntiMalwareCondition.class,
    LoggingCondition.class,
    DataProtectionCondition.class,
    FilteringConfigurationCondition.class
})
public class ConfigurationCondition {

    protected boolean isCNF;

    /**
     * Gets the value of the isCNF property.
     * 
     */
    public boolean isIsCNF() {
        return isCNF;
    }

    /**
     * Sets the value of the isCNF property.
     * 
     */
    public void setIsCNF(boolean value) {
        this.isCNF = value;
    }

}
