//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationAction")
@XmlSeeAlso({
    FiveGSecuritySliceAction.class,
    FiveGSecuredServiceAction.class,
    PrivacyAction.class,
    DataAggregationAction.class,
    AnonymityAction.class,
    MonitoringAction.class,
    NetworkSlicingAction.class,
    QoSAction.class,
    TrafficDivertAction.class,
    FilteringAction.class,
    ReduceBandwidthAction.class,
    CountAction.class,
    CheckAction.class,
    AntiMalwareAction.class,
    LoggingAction.class,
    RemoveAction.class,
    EnableAction.class,
    BootstrappingAction.class,
    PowerMgmtAction.class,
    VIoTHoneyNetAction.class,
    AuthorizationAction.class,
    AuthenticationAction.class,
    DataProtectionAction.class
})
public class ConfigurationAction {


}
