//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnforcementRequirements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnforcementRequirements"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enforcementDomains" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}EnforcementDomains"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnforcementRequirements", propOrder = {
    "enforcementDomains"
})
public class EnforcementRequirements {

    @XmlElement(required = true)
    protected EnforcementDomains enforcementDomains;

    /**
     * Gets the value of the enforcementDomains property.
     * 
     * @return
     *     possible object is
     *     {@link EnforcementDomains }
     *     
     */
    public EnforcementDomains getEnforcementDomains() {
        return enforcementDomains;
    }

    /**
     * Sets the value of the enforcementDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnforcementDomains }
     *     
     */
    public void setEnforcementDomains(EnforcementDomains value) {
        this.enforcementDomains = value;
    }

}
