//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FiveGSecuredServiceAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiveGSecuredServiceAction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fiveGSecuredServiceActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}FiveGSecuritySliceActionType"/&gt;
 *         &lt;element name="securedService" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}SecuredService"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiveGSecuredServiceAction", propOrder = {
    "fiveGSecuredServiceActionType",
    "securedService"
})
public class FiveGSecuredServiceAction
    extends ConfigurationAction
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FiveGSecuritySliceActionType fiveGSecuredServiceActionType;
    @XmlElement(required = true)
    protected SecuredService securedService;

    /**
     * Gets the value of the fiveGSecuredServiceActionType property.
     * 
     * @return
     *     possible object is
     *     {@link FiveGSecuritySliceActionType }
     *     
     */
    public FiveGSecuritySliceActionType getFiveGSecuredServiceActionType() {
        return fiveGSecuredServiceActionType;
    }

    /**
     * Sets the value of the fiveGSecuredServiceActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FiveGSecuritySliceActionType }
     *     
     */
    public void setFiveGSecuredServiceActionType(FiveGSecuritySliceActionType value) {
        this.fiveGSecuredServiceActionType = value;
    }

    /**
     * Gets the value of the securedService property.
     * 
     * @return
     *     possible object is
     *     {@link SecuredService }
     *     
     */
    public SecuredService getSecuredService() {
        return securedService;
    }

    /**
     * Sets the value of the securedService property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecuredService }
     *     
     */
    public void setSecuredService(SecuredService value) {
        this.securedService = value;
    }

}
