//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ITResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ITResourceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="configuration" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Configuration"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="dependencies" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Dependencies" minOccurs="0"/&gt;
 *         &lt;element name="enablerCandidates" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}EnablerCandidates" minOccurs="0"/&gt;
 *         &lt;element name="orchestrationRequirements" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}OrchestrationRequirements" minOccurs="0"/&gt;
 *         &lt;element name="enforcementRequirements" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}EnforcementRequirements" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orchestrationID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tenantID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sliceID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ITResourceType", propOrder = {
    "configuration",
    "priority",
    "dependencies",
    "enablerCandidates",
    "orchestrationRequirements",
    "enforcementRequirements"
})
public class ITResourceType {

    @XmlElement(required = true)
    protected Configuration configuration;
    protected BigInteger priority;
    protected Dependencies dependencies;
    protected EnablerCandidates enablerCandidates;
    protected OrchestrationRequirements orchestrationRequirements;
    protected EnforcementRequirements enforcementRequirements;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "orchestrationID")
    protected String orchestrationID;
    @XmlAttribute(name = "tenantID")
    protected String tenantID;
    @XmlAttribute(name = "sliceID")
    protected String sliceID;

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the enablerCandidates property.
     * 
     * @return
     *     possible object is
     *     {@link EnablerCandidates }
     *     
     */
    public EnablerCandidates getEnablerCandidates() {
        return enablerCandidates;
    }

    /**
     * Sets the value of the enablerCandidates property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnablerCandidates }
     *     
     */
    public void setEnablerCandidates(EnablerCandidates value) {
        this.enablerCandidates = value;
    }

    /**
     * Gets the value of the orchestrationRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link OrchestrationRequirements }
     *     
     */
    public OrchestrationRequirements getOrchestrationRequirements() {
        return orchestrationRequirements;
    }

    /**
     * Sets the value of the orchestrationRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrchestrationRequirements }
     *     
     */
    public void setOrchestrationRequirements(OrchestrationRequirements value) {
        this.orchestrationRequirements = value;
    }

    /**
     * Gets the value of the enforcementRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link EnforcementRequirements }
     *     
     */
    public EnforcementRequirements getEnforcementRequirements() {
        return enforcementRequirements;
    }

    /**
     * Sets the value of the enforcementRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnforcementRequirements }
     *     
     */
    public void setEnforcementRequirements(EnforcementRequirements value) {
        this.enforcementRequirements = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the orchestrationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrchestrationID() {
        return orchestrationID;
    }

    /**
     * Sets the value of the orchestrationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrchestrationID(String value) {
        this.orchestrationID = value;
    }

    /**
     * Gets the value of the tenantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantID() {
        return tenantID;
    }

    /**
     * Sets the value of the tenantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantID(String value) {
        this.tenantID = value;
    }

    /**
     * Gets the value of the sliceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSliceID() {
        return sliceID;
    }

    /**
     * Sets the value of the sliceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSliceID(String value) {
        this.sliceID = value;
    }

}
