//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//


package es.um.demo.models.itresource;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitoringActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MonitoringActionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALERT"/&gt;
 *     &lt;enumeration value="SECURITY_ANALYSIS"/&gt;
 *     &lt;enumeration value="ENABLE_SESS_STATS"/&gt;
 *     &lt;enumeration value="ENABLE_NO_SESS_STATS"/&gt;
 *     &lt;enumeration value="BEHAVIORAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MonitoringActionType")
@XmlEnum
public enum MonitoringActionType {

    ALERT,
    SECURITY_ANALYSIS,
    ENABLE_SESS_STATS,
    ENABLE_NO_SESS_STATS,
    BEHAVIORAL;

    public String value() {
        return name();
    }

    public static MonitoringActionType fromValue(String v) {
        return valueOf(v);
    }

}
