//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.22 at 01:37:53 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/IoTHoneynetSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.um.demo.models.iothoneynetschema;
